version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: auction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/auction
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key
    volumes:
      - .:/app
volumes:
  postgres_data: